### ISSUE TITLE
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x0a in position 160: truncated data when writing web logs

### ISSUE THREAD

**Issue by michelcrypt4d4mus** [beeware/std-nslog#40]
### Describe the bug

I have embedded a [Twisted](https://github.com/twisted/twisted/) web server in a briefcase application. Everything works OK until twisted goes to write some of its own logs at which point it crashes with an error about `utf-16-le`. This isn't an issue running outside of a briefcase build and the log message is very innocuous so i'm pretty sure `std-nslog` is responsible.

Specifically it is crashing on [this line](https://github.com/twisted/twisted/blob/trunk/src/twisted/web/http.py#L3324):
```python
logFile.write(line.encode("utf8"))
```

This is the line it is attempting to write when it crashes:

```
"127.0.0.1" - - [20/May/2024:01:41:19 +0000] "GET / HTTP/1.1" 302 200 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0"
```

It's interesting that it doesn't fail all the time - in fact it starts out just fine, passing through logs as expected. Then it gets to this line - the first line of actually logging server interactions - and it fails with `builtins.UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x0a in position 160: truncated data` (position 160 should be the final newline)

### Steps to reproduce

1. Launch a Twisted web server app that does anything
2. connect to it

### Expected behavior

`std-nslog` should not interfere with logging done by packages used by the app.

### Environment

```
- Operating System: macOS 13.6.4
- Python version: 3.12.3
- Software versions:
  - Briefcase: 0.3.18
  - Twisted: 24.3.0
```

### Logs

Stack trace of crash:
```
           2024-05-19T21:54:33-0400 [stdout#info] HERE IS LINE: "127.0.0.1" - - [20/May/2024:01:54:33 +0000] "GET / HTTP/1.1" 302 200 "-" "Mozilla/5.0 (Macintosh; subprocess.py:195
           Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0"
           2024-05-19T21:54:33-0400 [stdout#info] "127.0.0.1" - - [20/May/2024:01:54:33 +0000] "GET / HTTP/1.1" 302 200 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS  subprocess.py:195
           X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0"
           2024-05-19T21:54:33-0400 [twisted.web.server.Request#critical]                                                                                          subprocess.py:195
                   Traceback (most recent call last):                                                                                                              subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/app_packages/twisted/protocols/basic.py", line 549, in dataReceived
                       why = self.lineReceived(line)                                                                                                               subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/app_packages/twisted/web/http.py", line 2330, in lineReceived
                       self.allContentReceived()                                                                                                                   subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/app_packages/twisted/web/http.py", line 2463, in allContentReceived
                       req.requestReceived(command, path, version)                                                                                                 subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/app_packages/twisted/web/http.py", line 1019, in requestReceived
                       self.process()                                                                                                                              subprocess.py:195
                   --- <exception caught here> ---                                                                                                                 subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/app_packages/twisted/web/server.py", line 226, in process
                       self.render(resrc)                                                                                                                          subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/app_packages/twisted/web/server.py", line 382, in render
                       self.finish()                                                                                                                               subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/app_packages/twisted/web/server.py", line 276, in finish
                       return http.Request.finish(self)                                                                                                            subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/app_packages/twisted/web/http.py", line 1166, in finish
                       self.channel.factory.log(self)                                                                                                              subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/app_packages/twisted/web/http.py", line 3330, in log
                       logFile.write(line.encode("utf8"))                                                                                                          subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/app_packages/twisted/logger/_io.py", line 152, in write
                       text = message.decode(self._encoding)                                                                                                       subprocess.py:195
                     File "/Users/uzor/workspace/briefcase_app/build/briefcase_app/macos/app/BriefcaseApp.app/Contents/Resources/support/python-stdlib/encodings/utf_16_le.py", line 16, in decode
                       return codecs.utf_16_le_decode(input, errors, True)                                                                                         subprocess.py:195
                   builtins.UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x0a in position 160: truncated data                                           subprocess.py:195
                                                                      
```

**Comment by michelcrypt4d4mus** [comment]
[Twisted's logging](https://docs.twistedmatrix.com/en/twisted-20.3.0/core/howto/logger.html) is kind of nightmarishly complex but fwiw I have no special configuration in my app and b) i have tried all kinds of workarounds, most notably 

1. directing logs to a file (it writes the file instead of `stdout` but still crashes on this error, writing the stack trace to the file also) and 
2. configuring Twisted with a null logger that does nothing (which makes Twisted log nothing but still crash), presumably for the same reason)

One workaround is to go into the package and comment out on [the logging line](https://github.com/twisted/twisted/blob/trunk/src/twisted/web/http.py#L3324). Not the best workaround but it does allow briefcase to run my app. Looking for any kind of workaround that's less harsh than this one.

**Comment by freakboy3742** [comment]
Thanks for the report. I'm a little unclear as to what is being reported here - or, at least, why it's a problem with std-nslog. The stack trace you've provided makes no references to nslog - the only code referenced is in twisted or standard library code. There's nothing in std-nslog that is enforcing a 160 character limit; the sys.stdout shim that is installed should be able to accept any valid string. The only way I can see you'd get an issue is if you're writing *bytes*, or a badly encoded str object to stdout.

Are you able to provide a minimal test case that demonstrates the problem?

**Comment by michelcrypt4d4mus** [comment]
I think this is actually more a problem with Twisted - i opened [an issue](https://github.com/twisted/twisted/issues/12179) over there already. will close this one.
